
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage
from increment_sku import increment_sku
from add_roll import add_roll
from open_roll import open_roll
from empty_roll import empty_roll
from production import production_queue


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"assets/frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.attributes('-fullscreen', True)
window.configure(bg = "#10910D")
width= window.winfo_screenwidth()
height= window.winfo_screenheight()

canvas = Canvas(
    window,
    bg = "#10910D",
    height = height,
    width = width,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)

# image_1= background
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    width/2,
    height/2,
    image=image_image_1
)

# Button_1= Production Q
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: production_queue(),
    relief="flat"
)
button_1.place(
    x=width/2-243,
    y=238.0,
    width=202.0,
    height=55.0
)

# Button_2= Add To Stock
button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: increment_sku(),
    relief="flat"
)
button_2.place(
    x=width/2+41,
    y=151.0,
    width=202.0,
    height=55.0
)

# Button_3= Open Roll
button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: open_roll(),
    relief="flat"
)
button_3.place(
    x=width/2+41,
    y=64.0,
    width=202.0,
    height=55.0
)

# Button_4= Empty Roll
button_image_4 = PhotoImage(
    file=relative_to_assets("button_4.png"))
button_4 = Button(
    image=button_image_4,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: empty_roll(),
    relief="flat"
)
button_4.place(
    x=width/2-243,
    y=151.0,
    width=202.0,
    height=55.0
)

# Button_5= Add Roll
button_image_5 = PhotoImage(
    file=relative_to_assets("button_5.png"))
button_5 = Button(
    image=button_image_5,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: add_roll(),
    relief="flat"
)
button_5.place(
    x=width/2-243,
    y=64.0,
    width=202.0,
    height=55.0
)

# image_2= Title
image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    width/2,
    26.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
