name: Python and Flutter Build

on:
  push:
    branches: [ PreProd ]

jobs:
  build:
    runs-on: macos-12

    steps:
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '^14.0'
  
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11.6
      uses: actions/setup-python@v2
      with:
        python-version: 3.11.6

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
  
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.8' # La versión de Flutter que estás utilizando
        
    - name: 'Create env file'
      run: |
        touch .env
        echo APP_ENV=dev >> .env
        echo SERVICE_TOKEN=${{ secrets.INFISICAL_TOKEN }} >> .env
        cat .env

    - name: Build with Flet
      run: |
        flet build ipa --project "kumpe3dkiosk" --product "Kumpe3D Kiosk" --company "KumpeApps LLC" --org "com.kumpeapps.ios" --no-ios-splash --team 2T42Z3DM34 --build-version 0.0.1 --build-number 1


    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: package
        path: |
          build/
        if-no-files-found: error